theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
mathjax:
  version: "2.7.5"
  config: "MMLorHTML.js"

  jax:
    - "input/TeX"
    - "input/MathML"
    - "output/HTML-CSS"
    - "output/NativeMML"

  extensions:
    - "tex2jax.js"
    - "mml2jax.js"
    - "MathMenu.js"
    - "MathZoom.js"

  TeX:
    extensions:
      - "AMSmath.js"
      - "AMSsymbols.js"
      - "noErrors.js"
      - "noUndefined.js"