# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thesis Overload
email: joe.blazick@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is a Jekyll blog I started to keep track of work related to my Master's Thesis in Statistics.
baseurl: "/Mixed-Univariate-Gaussians" # the subpath of your site, e.g. /blog
url: "http://blazickjp.github.io" # the base hostname & protocol for your site
twitter_username: JoeBlazick
github_username:  blazickjp
# Build settings
markdown: kramdown